using System;
using System.Collections.Generic;

namespace FlowLyrics.Services;

public static class LocalizationService
{
	private static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> Translations = new Dictionary<string, IReadOnlyDictionary<string, string>>(StringComparer.OrdinalIgnoreCase)
	{
		["ja-JP"] = D(("Text", "文字"), ("Typography", "文字"), ("Font", "フォント"), ("Font Size", "文字サイズ"), ("Minimum Size", "最小サイズ"), ("Alignment", "揃え"), ("Left", "左"), ("Center", "中央"), ("Right", "右"), ("Active Position", "現在行の位置"), ("Top", "上"), ("Bottom", "下"), ("Line Spacing", "行間"), ("Line Display", "行表示"), ("Visible Lines", "表示行数"), ("Inactive Scale", "非選択行サイズ"), ("Previous Opacity", "前の行の濃さ"), ("Next Opacity", "次の行の濃さ"), ("Color", "色"), ("Color Preset", "カラープリセット"), ("Random", "ランダム"), ("Reset Colors", "色を初期化"), ("Custom Colors", "個別カラー"), ("Active Lyrics", "現在の歌詞"), ("Other Lyrics", "その他の歌詞"), ("Outline", "縁取り"), ("Shadow", "影"), ("Background", "背景"), ("Border", "枠"), ("Player UI", "プレイヤーUI"), ("Pick", "選択"), ("Effects & Surface", "効果と背景"), ("Shadow Distance", "影の距離"), ("Background Opacity", "背景の濃さ"), ("Window Opacity", "ウィンドウの濃さ"), ("Corner Radius", "角の丸み"), ("Padding", "余白"), ("Behavior", "表示・操作"), ("Lyrics Only", "歌詞のみ"), ("Components", "パーツ"), ("Track Info", "曲情報"), ("Player", "プレイヤー"), ("Seek Bar", "再生バー"), ("Border Width", "枠の太さ"), ("Window", "ウィンドウ"), ("Always on Top", "常に手前"), ("Hide when Paused", "停止中は隠す"), ("Show while Idle", "待機中も表示"), ("Plain Lyrics Fallback", "同期なし歌詞を表示"), ("Lock on Startup", "起動時にロック"), ("Start with Windows", "Windowsと同時起動"), ("Global Shortcuts", "グローバルショートカット"), ("Pause Eye Animation", "停止アイのアニメーション"), ("Lyrics Timing", "歌詞タイミング"), ("Language", "言語"), ("Reset", "初期値"), ("Cancel", "キャンセル"), ("Close", "閉じる"), ("FlowLyrics Settings", "FlowLyrics 設定"), ("Check settings", "設定を確認してください"), ("Select a font.", "フォントを選択してください。"), ("Reset all settings?", "初期値に戻しますか？"), ("Invalid color format. Use #FFFFFFFF or #FFFFFF.", "色を読み取れません。#FFFFFFFF または #FFFFFF 形式を使用してください。")),
		["zh-CN"] = D(("Text", "文字"), ("Typography", "字体"), ("Font", "字体"), ("Font Size", "字号"), ("Minimum Size", "最小字号"), ("Alignment", "对齐"), ("Left", "左"), ("Center", "居中"), ("Right", "右"), ("Active Position", "当前行位置"), ("Top", "顶部"), ("Bottom", "底部"), ("Line Spacing", "行距"), ("Line Display", "歌词行"), ("Visible Lines", "显示行数"), ("Inactive Scale", "非当前行缩放"), ("Previous Opacity", "上一行透明度"), ("Next Opacity", "下一行透明度"), ("Color", "颜色"), ("Color Preset", "颜色预设"), ("Random", "随机"), ("Reset Colors", "重置颜色"), ("Custom Colors", "自定义颜色"), ("Active Lyrics", "当前歌词"), ("Other Lyrics", "其他歌词"), ("Outline", "描边"), ("Shadow", "阴影"), ("Background", "背景"), ("Border", "边框"), ("Player UI", "播放器界面"), ("Pick", "选择"), ("Effects & Surface", "效果与表面"), ("Shadow Distance", "阴影距离"), ("Background Opacity", "背景不透明度"), ("Window Opacity", "窗口不透明度"), ("Corner Radius", "圆角"), ("Padding", "内边距"), ("Behavior", "显示与操作"), ("Lyrics Only", "仅歌词"), ("Components", "组件"), ("Track Info", "歌曲信息"), ("Player", "播放器"), ("Seek Bar", "进度条"), ("Border Width", "边框宽度"), ("Window", "窗口"), ("Always on Top", "始终置顶"), ("Hide when Paused", "暂停时隐藏"), ("Show while Idle", "空闲时显示"), ("Plain Lyrics Fallback", "显示非同步歌词"), ("Lock on Startup", "启动时锁定"), ("Start with Windows", "随 Windows 启动"), ("Global Shortcuts", "全局快捷键"), ("Pause Eye Animation", "暂停眼睛动画"), ("Lyrics Timing", "歌词时间"), ("Language", "语言"), ("Reset", "重置"), ("Cancel", "取消"), ("Close", "关闭"), ("FlowLyrics Settings", "FlowLyrics 设置"), ("Check settings", "请检查设置"), ("Select a font.", "请选择字体。"), ("Reset all settings?", "要重置所有设置吗？"), ("Invalid color format. Use #FFFFFFFF or #FFFFFF.", "颜色格式无效。请使用 #FFFFFFFF 或 #FFFFFF。")),
		["zh-TW"] = D(("Text", "文字"), ("Typography", "字型"), ("Font", "字型"), ("Font Size", "字體大小"), ("Minimum Size", "最小字體"), ("Alignment", "對齊"), ("Left", "左"), ("Center", "置中"), ("Right", "右"), ("Active Position", "目前行位置"), ("Top", "頂端"), ("Bottom", "底部"), ("Line Spacing", "行距"), ("Line Display", "歌詞行"), ("Visible Lines", "顯示行數"), ("Inactive Scale", "非目前行縮放"), ("Previous Opacity", "上一行透明度"), ("Next Opacity", "下一行透明度"), ("Color", "色彩"), ("Color Preset", "色彩預設"), ("Random", "隨機"), ("Reset Colors", "重設色彩"), ("Custom Colors", "自訂色彩"), ("Active Lyrics", "目前歌詞"), ("Other Lyrics", "其他歌詞"), ("Outline", "外框"), ("Shadow", "陰影"), ("Background", "背景"), ("Border", "邊框"), ("Player UI", "播放器介面"), ("Pick", "選擇"), ("Effects & Surface", "效果與表面"), ("Shadow Distance", "陰影距離"), ("Background Opacity", "背景不透明度"), ("Window Opacity", "視窗不透明度"), ("Corner Radius", "圓角"), ("Padding", "內距"), ("Behavior", "顯示與操作"), ("Lyrics Only", "僅歌詞"), ("Components", "元件"), ("Track Info", "歌曲資訊"), ("Player", "播放器"), ("Seek Bar", "進度列"), ("Border Width", "邊框寬度"), ("Window", "視窗"), ("Always on Top", "永遠置頂"), ("Hide when Paused", "暫停時隱藏"), ("Show while Idle", "閒置時顯示"), ("Plain Lyrics Fallback", "顯示非同步歌詞"), ("Lock on Startup", "啟動時鎖定"), ("Start with Windows", "隨 Windows 啟動"), ("Global Shortcuts", "全域快速鍵"), ("Pause Eye Animation", "暫停眼睛動畫"), ("Lyrics Timing", "歌詞時間"), ("Language", "語言"), ("Reset", "重設"), ("Cancel", "取消"), ("Close", "關閉"), ("FlowLyrics Settings", "FlowLyrics 設定"), ("Check settings", "請檢查設定"), ("Select a font.", "請選擇字型。"), ("Reset all settings?", "要重設所有設定嗎？"), ("Invalid color format. Use #FFFFFFFF or #FFFFFF.", "色彩格式無效。請使用 #FFFFFFFF 或 #FFFFFF。")),
		["ko-KR"] = D(("Text", "텍스트"), ("Typography", "글꼴"), ("Font", "글꼴"), ("Font Size", "글자 크기"), ("Minimum Size", "최소 크기"), ("Alignment", "정렬"), ("Left", "왼쪽"), ("Center", "가운데"), ("Right", "오른쪽"), ("Active Position", "현재 줄 위치"), ("Top", "위"), ("Bottom", "아래"), ("Line Spacing", "줄 간격"), ("Line Display", "줄 표시"), ("Visible Lines", "표시 줄 수"), ("Inactive Scale", "비활성 줄 크기"), ("Previous Opacity", "이전 줄 불투명도"), ("Next Opacity", "다음 줄 불투명도"), ("Color", "색상"), ("Color Preset", "색상 프리셋"), ("Random", "랜덤"), ("Reset Colors", "색상 초기화"), ("Custom Colors", "사용자 색상"), ("Active Lyrics", "현재 가사"), ("Other Lyrics", "다른 가사"), ("Outline", "외곽선"), ("Shadow", "그림자"), ("Background", "배경"), ("Border", "테두리"), ("Player UI", "플레이어 UI"), ("Pick", "선택"), ("Effects & Surface", "효과 및 배경"), ("Shadow Distance", "그림자 거리"), ("Background Opacity", "배경 불투명도"), ("Window Opacity", "창 불투명도"), ("Corner Radius", "모서리 둥글기"), ("Padding", "여백"), ("Behavior", "표시 및 동작"), ("Lyrics Only", "가사만"), ("Components", "구성 요소"), ("Track Info", "곡 정보"), ("Player", "플레이어"), ("Seek Bar", "재생 바"), ("Border Width", "테두리 두께"), ("Window", "창"), ("Always on Top", "항상 위"), ("Hide when Paused", "일시정지 시 숨기기"), ("Show while Idle", "대기 중 표시"), ("Plain Lyrics Fallback", "일반 가사 표시"), ("Lock on Startup", "시작할 때 잠금"), ("Start with Windows", "Windows 시작 시 실행"), ("Global Shortcuts", "전역 단축키"), ("Pause Eye Animation", "일시정지 눈 애니메이션"), ("Lyrics Timing", "가사 타이밍"), ("Language", "언어"), ("Reset", "초기화"), ("Cancel", "취소"), ("Close", "닫기"), ("FlowLyrics Settings", "FlowLyrics 설정"), ("Check settings", "설정을 확인하세요"), ("Select a font.", "글꼴을 선택하세요."), ("Reset all settings?", "모든 설정을 초기화할까요?"), ("Invalid color format. Use #FFFFFFFF or #FFFFFF.", "색상 형식이 올바르지 않습니다. #FFFFFFFF 또는 #FFFFFF를 사용하세요.")),
		["es-ES"] = D(("Text", "Texto"), ("Typography", "Tipografía"), ("Font", "Fuente"), ("Font Size", "Tamaño"), ("Minimum Size", "Tamaño mínimo"), ("Alignment", "Alineación"), ("Left", "Izquierda"), ("Center", "Centro"), ("Right", "Derecha"), ("Active Position", "Posición activa"), ("Top", "Arriba"), ("Bottom", "Abajo"), ("Line Spacing", "Espaciado"), ("Line Display", "Líneas"), ("Visible Lines", "Líneas visibles"), ("Inactive Scale", "Escala inactiva"), ("Previous Opacity", "Opacidad anterior"), ("Next Opacity", "Opacidad siguiente"), ("Color", "Color"), ("Color Preset", "Paleta de color"), ("Random", "Aleatorio"), ("Reset Colors", "Restablecer colores"), ("Custom Colors", "Colores personalizados"), ("Active Lyrics", "Letra activa"), ("Other Lyrics", "Otras letras"), ("Outline", "Contorno"), ("Shadow", "Sombra"), ("Background", "Fondo"), ("Border", "Borde"), ("Player UI", "Interfaz del reproductor"), ("Pick", "Elegir"), ("Effects & Surface", "Efectos y superficie"), ("Shadow Distance", "Distancia de sombra"), ("Background Opacity", "Opacidad del fondo"), ("Window Opacity", "Opacidad de ventana"), ("Corner Radius", "Radio de esquina"), ("Padding", "Margen interior"), ("Behavior", "Vista y control"), ("Lyrics Only", "Solo letra"), ("Components", "Componentes"), ("Track Info", "Información de canción"), ("Player", "Reproductor"), ("Seek Bar", "Barra de progreso"), ("Border Width", "Ancho del borde"), ("Window", "Ventana"), ("Always on Top", "Siempre visible"), ("Hide when Paused", "Ocultar al pausar"), ("Show while Idle", "Mostrar en espera"), ("Plain Lyrics Fallback", "Mostrar letra sin sincronizar"), ("Lock on Startup", "Bloquear al iniciar"), ("Start with Windows", "Iniciar con Windows"), ("Global Shortcuts", "Atajos globales"), ("Pause Eye Animation", "Animación de ojos en pausa"), ("Lyrics Timing", "Tiempo de letra"), ("Language", "Idioma"), ("Reset", "Restablecer"), ("Cancel", "Cancelar"), ("Close", "Cerrar"), ("FlowLyrics Settings", "Ajustes de FlowLyrics"), ("Check settings", "Revisa los ajustes"), ("Select a font.", "Selecciona una fuente."), ("Reset all settings?", "¿Restablecer todos los ajustes?"), ("Invalid color format. Use #FFFFFFFF or #FFFFFF.", "Formato de color no válido. Usa #FFFFFFFF o #FFFFFF.")),
		["fr-FR"] = D(("Text", "Texte"), ("Typography", "Typographie"), ("Font", "Police"), ("Font Size", "Taille"), ("Minimum Size", "Taille minimale"), ("Alignment", "Alignement"), ("Left", "Gauche"), ("Center", "Centre"), ("Right", "Droite"), ("Active Position", "Position active"), ("Top", "Haut"), ("Bottom", "Bas"), ("Line Spacing", "Interligne"), ("Line Display", "Lignes"), ("Visible Lines", "Lignes visibles"), ("Inactive Scale", "Échelle inactive"), ("Previous Opacity", "Opacité précédente"), ("Next Opacity", "Opacité suivante"), ("Color", "Couleur"), ("Color Preset", "Préréglage couleur"), ("Random", "Aléatoire"), ("Reset Colors", "Réinitialiser les couleurs"), ("Custom Colors", "Couleurs personnalisées"), ("Active Lyrics", "Paroles actives"), ("Other Lyrics", "Autres paroles"), ("Outline", "Contour"), ("Shadow", "Ombre"), ("Background", "Arrière-plan"), ("Border", "Bordure"), ("Player UI", "Interface lecteur"), ("Pick", "Choisir"), ("Effects & Surface", "Effets et surface"), ("Shadow Distance", "Distance de l’ombre"), ("Background Opacity", "Opacité du fond"), ("Window Opacity", "Opacité de la fenêtre"), ("Corner Radius", "Arrondi"), ("Padding", "Marge interne"), ("Behavior", "Affichage et contrôle"), ("Lyrics Only", "Paroles seules"), ("Components", "Composants"), ("Track Info", "Infos du morceau"), ("Player", "Lecteur"), ("Seek Bar", "Barre de lecture"), ("Border Width", "Largeur de bordure"), ("Window", "Fenêtre"), ("Always on Top", "Toujours au premier plan"), ("Hide when Paused", "Masquer en pause"), ("Show while Idle", "Afficher en attente"), ("Plain Lyrics Fallback", "Afficher les paroles non synchronisées"), ("Lock on Startup", "Verrouiller au démarrage"), ("Start with Windows", "Démarrer avec Windows"), ("Global Shortcuts", "Raccourcis globaux"), ("Pause Eye Animation", "Animation des yeux en pause"), ("Lyrics Timing", "Synchronisation des paroles"), ("Language", "Langue"), ("Reset", "Réinitialiser"), ("Cancel", "Annuler"), ("Close", "Fermer"), ("FlowLyrics Settings", "Paramètres de FlowLyrics"), ("Check settings", "Vérifiez les paramètres"), ("Select a font.", "Sélectionnez une police."), ("Reset all settings?", "Réinitialiser tous les paramètres ?"), ("Invalid color format. Use #FFFFFFFF or #FFFFFF.", "Format de couleur invalide. Utilisez #FFFFFFFF ou #FFFFFF.")),
		["de-DE"] = D(("Text", "Text"), ("Typography", "Typografie"), ("Font", "Schriftart"), ("Font Size", "Schriftgröße"), ("Minimum Size", "Mindestgröße"), ("Alignment", "Ausrichtung"), ("Left", "Links"), ("Center", "Mitte"), ("Right", "Rechts"), ("Active Position", "Aktive Position"), ("Top", "Oben"), ("Bottom", "Unten"), ("Line Spacing", "Zeilenabstand"), ("Line Display", "Zeilenanzeige"), ("Visible Lines", "Sichtbare Zeilen"), ("Inactive Scale", "Inaktive Skalierung"), ("Previous Opacity", "Deckkraft davor"), ("Next Opacity", "Deckkraft danach"), ("Color", "Farbe"), ("Color Preset", "Farbvorlage"), ("Random", "Zufällig"), ("Reset Colors", "Farben zurücksetzen"), ("Custom Colors", "Eigene Farben"), ("Active Lyrics", "Aktiver Text"), ("Other Lyrics", "Anderer Text"), ("Outline", "Kontur"), ("Shadow", "Schatten"), ("Background", "Hintergrund"), ("Border", "Rahmen"), ("Player UI", "Player-Oberfläche"), ("Pick", "Wählen"), ("Effects & Surface", "Effekte und Oberfläche"), ("Shadow Distance", "Schattenabstand"), ("Background Opacity", "Hintergrunddeckkraft"), ("Window Opacity", "Fensterdeckkraft"), ("Corner Radius", "Eckenradius"), ("Padding", "Innenabstand"), ("Behavior", "Anzeige und Steuerung"), ("Lyrics Only", "Nur Liedtext"), ("Components", "Komponenten"), ("Track Info", "Titelinfo"), ("Player", "Player"), ("Seek Bar", "Wiedergabeleiste"), ("Border Width", "Rahmenbreite"), ("Window", "Fenster"), ("Always on Top", "Immer im Vordergrund"), ("Hide when Paused", "Bei Pause ausblenden"), ("Show while Idle", "Im Leerlauf anzeigen"), ("Plain Lyrics Fallback", "Unsynchronisierten Text anzeigen"), ("Lock on Startup", "Beim Start sperren"), ("Start with Windows", "Mit Windows starten"), ("Global Shortcuts", "Globale Tastenkürzel"), ("Pause Eye Animation", "Augenanimation bei Pause"), ("Lyrics Timing", "Liedtext-Timing"), ("Language", "Sprache"), ("Reset", "Zurücksetzen"), ("Cancel", "Abbrechen"), ("Close", "Schließen"), ("FlowLyrics Settings", "FlowLyrics-Einstellungen"), ("Check settings", "Einstellungen prüfen"), ("Select a font.", "Wählen Sie eine Schriftart."), ("Reset all settings?", "Alle Einstellungen zurücksetzen?"), ("Invalid color format. Use #FFFFFFFF or #FFFFFF.", "Ungültiges Farbformat. Verwenden Sie #FFFFFFFF oder #FFFFFF.")),
		["pt-BR"] = D(("Text", "Texto"), ("Typography", "Tipografia"), ("Font", "Fonte"), ("Font Size", "Tamanho"), ("Minimum Size", "Tamanho mínimo"), ("Alignment", "Alinhamento"), ("Left", "Esquerda"), ("Center", "Centro"), ("Right", "Direita"), ("Active Position", "Posição ativa"), ("Top", "Topo"), ("Bottom", "Base"), ("Line Spacing", "Espaçamento"), ("Line Display", "Linhas"), ("Visible Lines", "Linhas visíveis"), ("Inactive Scale", "Escala inativa"), ("Previous Opacity", "Opacidade anterior"), ("Next Opacity", "Opacidade seguinte"), ("Color", "Cor"), ("Color Preset", "Predefinição de cor"), ("Random", "Aleatório"), ("Reset Colors", "Redefinir cores"), ("Custom Colors", "Cores personalizadas"), ("Active Lyrics", "Letra ativa"), ("Other Lyrics", "Outras letras"), ("Outline", "Contorno"), ("Shadow", "Sombra"), ("Background", "Fundo"), ("Border", "Borda"), ("Player UI", "Interface do player"), ("Pick", "Escolher"), ("Effects & Surface", "Efeitos e superfície"), ("Shadow Distance", "Distância da sombra"), ("Background Opacity", "Opacidade do fundo"), ("Window Opacity", "Opacidade da janela"), ("Corner Radius", "Raio dos cantos"), ("Padding", "Espaço interno"), ("Behavior", "Exibição e controle"), ("Lyrics Only", "Somente letra"), ("Components", "Componentes"), ("Track Info", "Informações da faixa"), ("Player", "Player"), ("Seek Bar", "Barra de reprodução"), ("Border Width", "Largura da borda"), ("Window", "Janela"), ("Always on Top", "Sempre visível"), ("Hide when Paused", "Ocultar ao pausar"), ("Show while Idle", "Mostrar em espera"), ("Plain Lyrics Fallback", "Mostrar letra sem sincronização"), ("Lock on Startup", "Bloquear ao iniciar"), ("Start with Windows", "Iniciar com o Windows"), ("Global Shortcuts", "Atalhos globais"), ("Pause Eye Animation", "Animação dos olhos em pausa"), ("Lyrics Timing", "Tempo da letra"), ("Language", "Idioma"), ("Reset", "Redefinir"), ("Cancel", "Cancelar"), ("Close", "Fechar"), ("FlowLyrics Settings", "Configurações do FlowLyrics"), ("Check settings", "Verifique as configurações"), ("Select a font.", "Selecione uma fonte."), ("Reset all settings?", "Redefinir todas as configurações?"), ("Invalid color format. Use #FFFFFFFF or #FFFFFF.", "Formato de cor inválido. Use #FFFFFFFF ou #FFFFFF.")),
		["ru-RU"] = D(("Text", "Текст"), ("Typography", "Типографика"), ("Font", "Шрифт"), ("Font Size", "Размер шрифта"), ("Minimum Size", "Минимальный размер"), ("Alignment", "Выравнивание"), ("Left", "Слева"), ("Center", "По центру"), ("Right", "Справа"), ("Active Position", "Позиция строки"), ("Top", "Сверху"), ("Bottom", "Снизу"), ("Line Spacing", "Интервал строк"), ("Line Display", "Строки"), ("Visible Lines", "Видимые строки"), ("Inactive Scale", "Размер неактивных"), ("Previous Opacity", "Прозрачность предыдущих"), ("Next Opacity", "Прозрачность следующих"), ("Color", "Цвет"), ("Color Preset", "Набор цветов"), ("Random", "Случайно"), ("Reset Colors", "Сбросить цвета"), ("Custom Colors", "Свои цвета"), ("Active Lyrics", "Активная строка"), ("Other Lyrics", "Другие строки"), ("Outline", "Контур"), ("Shadow", "Тень"), ("Background", "Фон"), ("Border", "Рамка"), ("Player UI", "Интерфейс плеера"), ("Pick", "Выбрать"), ("Effects & Surface", "Эффекты и фон"), ("Shadow Distance", "Смещение тени"), ("Background Opacity", "Непрозрачность фона"), ("Window Opacity", "Непрозрачность окна"), ("Corner Radius", "Скругление"), ("Padding", "Отступ"), ("Behavior", "Вид и управление"), ("Lyrics Only", "Только текст"), ("Components", "Компоненты"), ("Track Info", "Информация о треке"), ("Player", "Плеер"), ("Seek Bar", "Полоса прокрутки"), ("Border Width", "Ширина рамки"), ("Window", "Окно"), ("Always on Top", "Поверх всех окон"), ("Hide when Paused", "Скрывать на паузе"), ("Show while Idle", "Показывать в ожидании"), ("Plain Lyrics Fallback", "Показывать несинхронный текст"), ("Lock on Startup", "Блокировать при запуске"), ("Start with Windows", "Запускать с Windows"), ("Global Shortcuts", "Глобальные сочетания"), ("Pause Eye Animation", "Анимация глаз на паузе"), ("Lyrics Timing", "Сдвиг текста"), ("Language", "Язык"), ("Reset", "Сбросить"), ("Cancel", "Отмена"), ("Close", "Закрыть"), ("FlowLyrics Settings", "Настройки FlowLyrics"), ("Check settings", "Проверьте настройки"), ("Select a font.", "Выберите шрифт."), ("Reset all settings?", "Сбросить все настройки?"), ("Invalid color format. Use #FFFFFFFF or #FFFFFF.", "Неверный формат цвета. Используйте #FFFFFFFF или #FFFFFF."))
	};

	private static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> OverlayTranslations = new Dictionary<string, IReadOnlyDictionary<string, string>>(StringComparer.OrdinalIgnoreCase)
	{
		["ja-JP"] = D(("Settings...", "設定..."), ("Lock", "ロック"), ("Unlock", "ロック解除"), ("Hide overlay", "表示を隠す"), ("Spotify controls", "Spotifyを操作"), ("Previous track", "前の曲"), ("Play / Pause", "再生／一時停止"), ("Next track", "次の曲"), ("Current track", "現在の曲"), ("Reload lyrics", "歌詞を再取得"), ("Import LRC...", "LRCファイルを読み込む..."), ("Clear saved lyrics", "保存済み歌詞を削除"), ("Lyrics timing", "歌詞タイミング"), ("0.1 s earlier", "0.1秒早める"), ("0.5 s earlier", "0.5秒早める"), ("0.1 s later", "0.1秒遅らせる"), ("0.5 s later", "0.5秒遅らせる"), ("Reset track timing", "この曲の補正をリセット"), ("Exit FlowLyrics", "FlowLyricsを終了"), ("Lock / Unlock", "ロック／解除"), ("Locked — click to unlock", "ロック中（クリックで解除）"), ("Lock — click to enable", "ロック（クリックで有効化）"), ("Volume", "音量"), ("Local LRC", "ローカルLRC"), ("LRC Folder", "LRCフォルダ"), ("Open Folder", "フォルダを開く"), ("Place .lrc files here. Use “Artist - Title.lrc” or “Title.lrc”. Changes are detected automatically.", "ここに .lrc を入れてください。ファイル名は「アーティスト - 曲名.lrc」または「曲名.lrc」にします。変更は自動検出されます。"), ("Could not open the folder.", "フォルダを開けませんでした"), ("Add an LRC file from Settings > Local LRC.", "設定 > ローカルLRCからLRCファイルを追加してください。")),
		["zh-CN"] = D(("Settings...", "设置..."), ("Lock", "锁定"), ("Unlock", "解锁"), ("Hide overlay", "隐藏悬浮窗"), ("Spotify controls", "Spotify 控制"), ("Previous track", "上一曲"), ("Play / Pause", "播放／暂停"), ("Next track", "下一曲"), ("Current track", "当前歌曲"), ("Reload lyrics", "重新获取歌词"), ("Import LRC...", "导入 LRC..."), ("Clear saved lyrics", "清除已保存歌词"), ("Lyrics timing", "歌词时间"), ("0.1 s earlier", "提前 0.1 秒"), ("0.5 s earlier", "提前 0.5 秒"), ("0.1 s later", "延后 0.1 秒"), ("0.5 s later", "延后 0.5 秒"), ("Reset track timing", "重置本曲时间"), ("Exit FlowLyrics", "退出 FlowLyrics"), ("Lock / Unlock", "锁定／解锁"), ("Locked — click to unlock", "已锁定—点击解锁"), ("Lock — click to enable", "点击锁定"), ("Volume", "音量"), ("Local LRC", "本地 LRC"), ("LRC Folder", "LRC 文件夹"), ("Open Folder", "打开文件夹"), ("Place .lrc files here. Use “Artist - Title.lrc” or “Title.lrc”. Changes are detected automatically.", "请将 .lrc 文件放在这里，文件名使用“歌手 - 歌名.lrc”或“歌名.lrc”。更改会自动检测。"), ("Could not open the folder.", "无法打开文件夹"), ("Add an LRC file from Settings > Local LRC.", "请从设置 > 本地 LRC 添加 LRC 文件。")),
		["zh-TW"] = D(("Settings...", "設定..."), ("Lock", "鎖定"), ("Unlock", "解鎖"), ("Hide overlay", "隱藏浮窗"), ("Spotify controls", "Spotify 控制"), ("Previous track", "上一首"), ("Play / Pause", "播放／暫停"), ("Next track", "下一首"), ("Current track", "目前歌曲"), ("Reload lyrics", "重新取得歌詞"), ("Import LRC...", "匯入 LRC..."), ("Clear saved lyrics", "清除已儲存歌詞"), ("Lyrics timing", "歌詞時間"), ("0.1 s earlier", "提前 0.1 秒"), ("0.5 s earlier", "提前 0.5 秒"), ("0.1 s later", "延後 0.1 秒"), ("0.5 s later", "延後 0.5 秒"), ("Reset track timing", "重設本曲時間"), ("Exit FlowLyrics", "結束 FlowLyrics"), ("Lock / Unlock", "鎖定／解鎖"), ("Locked — click to unlock", "已鎖定—點擊解鎖"), ("Lock — click to enable", "點擊鎖定"), ("Volume", "音量"), ("Local LRC", "本機 LRC"), ("LRC Folder", "LRC 資料夾"), ("Open Folder", "開啟資料夾"), ("Place .lrc files here. Use “Artist - Title.lrc” or “Title.lrc”. Changes are detected automatically.", "請將 .lrc 檔案放在這裡，檔名使用「歌手 - 歌名.lrc」或「歌名.lrc」。變更會自動偵測。"), ("Could not open the folder.", "無法開啟資料夾"), ("Add an LRC file from Settings > Local LRC.", "請從設定 > 本機 LRC 加入 LRC 檔案。")),
		["ko-KR"] = D(("Settings...", "설정..."), ("Lock", "잠금"), ("Unlock", "잠금 해제"), ("Hide overlay", "오버레이 숨기기"), ("Spotify controls", "Spotify 제어"), ("Previous track", "이전 곡"), ("Play / Pause", "재생／일시정지"), ("Next track", "다음 곡"), ("Current track", "현재 곡"), ("Reload lyrics", "가사 다시 받기"), ("Import LRC...", "LRC 가져오기..."), ("Clear saved lyrics", "저장된 가사 삭제"), ("Lyrics timing", "가사 타이밍"), ("0.1 s earlier", "0.1초 빠르게"), ("0.5 s earlier", "0.5초 빠르게"), ("0.1 s later", "0.1초 느리게"), ("0.5 s later", "0.5초 느리게"), ("Reset track timing", "현재 곡 타이밍 초기화"), ("Exit FlowLyrics", "FlowLyrics 종료"), ("Lock / Unlock", "잠금／해제"), ("Locked — click to unlock", "잠김—클릭하여 해제"), ("Lock — click to enable", "클릭하여 잠금"), ("Volume", "음량"), ("Local LRC", "로컬 LRC"), ("LRC Folder", "LRC 폴더"), ("Open Folder", "폴더 열기"), ("Place .lrc files here. Use “Artist - Title.lrc” or “Title.lrc”. Changes are detected automatically.", "여기에 .lrc 파일을 넣으세요. 파일명은 ‘아티스트 - 곡명.lrc’ 또는 ‘곡명.lrc’를 사용합니다. 변경 사항은 자동 감지됩니다."), ("Could not open the folder.", "폴더를 열 수 없습니다"), ("Add an LRC file from Settings > Local LRC.", "설정 > 로컬 LRC에서 LRC 파일을 추가하세요.")),
		["es-ES"] = D(("Settings...", "Ajustes..."), ("Lock", "Bloquear"), ("Unlock", "Desbloquear"), ("Hide overlay", "Ocultar panel"), ("Spotify controls", "Controles de Spotify"), ("Previous track", "Pista anterior"), ("Play / Pause", "Reproducir／Pausar"), ("Next track", "Pista siguiente"), ("Current track", "Pista actual"), ("Reload lyrics", "Recargar letra"), ("Import LRC...", "Importar LRC..."), ("Clear saved lyrics", "Borrar letra guardada"), ("Lyrics timing", "Tiempo de letra"), ("0.1 s earlier", "0,1 s antes"), ("0.5 s earlier", "0,5 s antes"), ("0.1 s later", "0,1 s después"), ("0.5 s later", "0,5 s después"), ("Reset track timing", "Restablecer tiempo"), ("Exit FlowLyrics", "Salir de FlowLyrics"), ("Lock / Unlock", "Bloquear／Desbloquear"), ("Locked — click to unlock", "Bloqueado—clic para desbloquear"), ("Lock — click to enable", "Clic para bloquear"), ("Volume", "Volumen"), ("Local LRC", "LRC local"), ("LRC Folder", "Carpeta LRC"), ("Open Folder", "Abrir carpeta"), ("Place .lrc files here. Use “Artist - Title.lrc” or “Title.lrc”. Changes are detected automatically.", "Coloca aquí los archivos .lrc. Usa “Artista - Título.lrc” o “Título.lrc”. Los cambios se detectan automáticamente."), ("Could not open the folder.", "No se pudo abrir la carpeta"), ("Add an LRC file from Settings > Local LRC.", "Añade un archivo LRC desde Ajustes > LRC local.")),
		["fr-FR"] = D(("Settings...", "Paramètres..."), ("Lock", "Verrouiller"), ("Unlock", "Déverrouiller"), ("Hide overlay", "Masquer l’affichage"), ("Spotify controls", "Contrôles Spotify"), ("Previous track", "Titre précédent"), ("Play / Pause", "Lecture／Pause"), ("Next track", "Titre suivant"), ("Current track", "Titre actuel"), ("Reload lyrics", "Recharger les paroles"), ("Import LRC...", "Importer un LRC..."), ("Clear saved lyrics", "Effacer les paroles enregistrées"), ("Lyrics timing", "Synchronisation"), ("0.1 s earlier", "0,1 s plus tôt"), ("0.5 s earlier", "0,5 s plus tôt"), ("0.1 s later", "0,1 s plus tard"), ("0.5 s later", "0,5 s plus tard"), ("Reset track timing", "Réinitialiser la synchronisation"), ("Exit FlowLyrics", "Quitter FlowLyrics"), ("Lock / Unlock", "Verrouiller／Déverrouiller"), ("Locked — click to unlock", "Verrouillé—cliquez pour déverrouiller"), ("Lock — click to enable", "Cliquez pour verrouiller"), ("Volume", "Volume"), ("Local LRC", "LRC local"), ("LRC Folder", "Dossier LRC"), ("Open Folder", "Ouvrir le dossier"), ("Place .lrc files here. Use “Artist - Title.lrc” or “Title.lrc”. Changes are detected automatically.", "Placez les fichiers .lrc ici. Utilisez « Artiste - Titre.lrc » ou « Titre.lrc ». Les changements sont détectés automatiquement."), ("Could not open the folder.", "Impossible d’ouvrir le dossier"), ("Add an LRC file from Settings > Local LRC.", "Ajoutez un fichier LRC depuis Paramètres > LRC local.")),
		["de-DE"] = D(("Settings...", "Einstellungen..."), ("Lock", "Sperren"), ("Unlock", "Entsperren"), ("Hide overlay", "Overlay ausblenden"), ("Spotify controls", "Spotify-Steuerung"), ("Previous track", "Vorheriger Titel"), ("Play / Pause", "Wiedergabe／Pause"), ("Next track", "Nächster Titel"), ("Current track", "Aktueller Titel"), ("Reload lyrics", "Liedtext neu laden"), ("Import LRC...", "LRC importieren..."), ("Clear saved lyrics", "Gespeicherten Text löschen"), ("Lyrics timing", "Liedtext-Timing"), ("0.1 s earlier", "0,1 s früher"), ("0.5 s earlier", "0,5 s früher"), ("0.1 s later", "0,1 s später"), ("0.5 s later", "0,5 s später"), ("Reset track timing", "Timing zurücksetzen"), ("Exit FlowLyrics", "FlowLyrics beenden"), ("Lock / Unlock", "Sperren／Entsperren"), ("Locked — click to unlock", "Gesperrt—zum Entsperren klicken"), ("Lock — click to enable", "Zum Sperren klicken"), ("Volume", "Lautstärke"), ("Local LRC", "Lokale LRC"), ("LRC Folder", "LRC-Ordner"), ("Open Folder", "Ordner öffnen"), ("Place .lrc files here. Use “Artist - Title.lrc” or “Title.lrc”. Changes are detected automatically.", "Legen Sie .lrc-Dateien hier ab. Verwenden Sie „Künstler - Titel.lrc“ oder „Titel.lrc“. Änderungen werden automatisch erkannt."), ("Could not open the folder.", "Ordner konnte nicht geöffnet werden"), ("Add an LRC file from Settings > Local LRC.", "Fügen Sie eine LRC-Datei unter Einstellungen > Lokale LRC hinzu.")),
		["pt-BR"] = D(("Settings...", "Configurações..."), ("Lock", "Bloquear"), ("Unlock", "Desbloquear"), ("Hide overlay", "Ocultar sobreposição"), ("Spotify controls", "Controles do Spotify"), ("Previous track", "Faixa anterior"), ("Play / Pause", "Reproduzir／Pausar"), ("Next track", "Próxima faixa"), ("Current track", "Faixa atual"), ("Reload lyrics", "Recarregar letra"), ("Import LRC...", "Importar LRC..."), ("Clear saved lyrics", "Apagar letra salva"), ("Lyrics timing", "Tempo da letra"), ("0.1 s earlier", "0,1 s antes"), ("0.5 s earlier", "0,5 s antes"), ("0.1 s later", "0,1 s depois"), ("0.5 s later", "0,5 s depois"), ("Reset track timing", "Redefinir tempo"), ("Exit FlowLyrics", "Sair do FlowLyrics"), ("Lock / Unlock", "Bloquear／Desbloquear"), ("Locked — click to unlock", "Bloqueado—clique para desbloquear"), ("Lock — click to enable", "Clique para bloquear"), ("Volume", "Volume"), ("Local LRC", "LRC local"), ("LRC Folder", "Pasta LRC"), ("Open Folder", "Abrir pasta"), ("Place .lrc files here. Use “Artist - Title.lrc” or “Title.lrc”. Changes are detected automatically.", "Coloque os arquivos .lrc aqui. Use “Artista - Título.lrc” ou “Título.lrc”. As alterações são detectadas automaticamente."), ("Could not open the folder.", "Não foi possível abrir a pasta"), ("Add an LRC file from Settings > Local LRC.", "Adicione um arquivo LRC em Configurações > LRC local.")),
		["ru-RU"] = D(("Settings...", "Настройки..."), ("Lock", "Заблокировать"), ("Unlock", "Разблокировать"), ("Hide overlay", "Скрыть окно"), ("Spotify controls", "Управление Spotify"), ("Previous track", "Предыдущий трек"), ("Play / Pause", "Воспроизведение／Пауза"), ("Next track", "Следующий трек"), ("Current track", "Текущий трек"), ("Reload lyrics", "Обновить текст"), ("Import LRC...", "Импорт LRC..."), ("Clear saved lyrics", "Удалить сохранённый текст"), ("Lyrics timing", "Сдвиг текста"), ("0.1 s earlier", "На 0,1 с раньше"), ("0.5 s earlier", "На 0,5 с раньше"), ("0.1 s later", "На 0,1 с позже"), ("0.5 s later", "На 0,5 с позже"), ("Reset track timing", "Сбросить сдвиг трека"), ("Exit FlowLyrics", "Выйти из FlowLyrics"), ("Lock / Unlock", "Блокировка／Разблокировка"), ("Locked — click to unlock", "Заблокировано—нажмите для разблокировки"), ("Lock — click to enable", "Нажмите для блокировки"), ("Volume", "Громкость"), ("Local LRC", "Локальный LRC"), ("LRC Folder", "Папка LRC"), ("Open Folder", "Открыть папку"), ("Place .lrc files here. Use “Artist - Title.lrc” or “Title.lrc”. Changes are detected automatically.", "Поместите файлы .lrc сюда. Используйте «Исполнитель - Название.lrc» или «Название.lrc». Изменения определяются автоматически."), ("Could not open the folder.", "Не удалось открыть папку"), ("Add an LRC file from Settings > Local LRC.", "Добавьте файл LRC через Настройки > Локальный LRC."))
	};

	private static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> LyricsGuidanceTranslations = new Dictionary<string, IReadOnlyDictionary<string, string>>(StringComparer.OrdinalIgnoreCase)
	{
		["ja-JP"] = D(("Play a track on Spotify.", "Spotifyで曲を再生してください。"), ("If the lyrics or timing are incorrect, you can choose another result from LRCLIB.", "歌詞やタイミングが違う場合は、LRCLIBから別の候補を選択できます。"), ("Estimated timing is being used. Choose from LRCLIB to look for synchronized lyrics.", "簡易同期を使用中です。LRCLIBから候補を選び、同期歌詞を探せます。"), ("Lyrics candidates were found in LRCLIB. Choose the correct lyrics below.", "LRCLIBに歌詞候補が見つかりました。下から正しい歌詞を選択してください。"), ("No synced lyrics were found. Search using another title or English name, or add a local LRC file.", "同期歌詞が見つかりませんでした。別の曲名・英語名で検索するか、ローカルLRCを追加してください。")),
		["zh-CN"] = D(("Play a track on Spotify.", "请在 Spotify 中播放歌曲。"), ("If the lyrics or timing are incorrect, you can choose another result from LRCLIB.", "如果歌词或时间不正确，可以从 LRCLIB 选择其他结果。"), ("Estimated timing is being used. Choose from LRCLIB to look for synchronized lyrics.", "正在使用估算时间。可从 LRCLIB 选择候选以查找同步歌词。"), ("Lyrics candidates were found in LRCLIB. Choose the correct lyrics below.", "在 LRCLIB 中找到了歌词候选。请在下方选择正确的歌词。"), ("No synced lyrics were found. Search using another title or English name, or add a local LRC file.", "未找到同步歌词。请使用其他曲名或英文名搜索，或添加本地 LRC 文件。")),
		["zh-TW"] = D(("Play a track on Spotify.", "請在 Spotify 播放歌曲。"), ("If the lyrics or timing are incorrect, you can choose another result from LRCLIB.", "如果歌詞或時間不正確，可以從 LRCLIB 選擇其他結果。"), ("Estimated timing is being used. Choose from LRCLIB to look for synchronized lyrics.", "目前使用估算時間。可從 LRCLIB 選擇候選以尋找同步歌詞。"), ("Lyrics candidates were found in LRCLIB. Choose the correct lyrics below.", "在 LRCLIB 找到歌詞候選。請在下方選擇正確的歌詞。"), ("No synced lyrics were found. Search using another title or English name, or add a local LRC file.", "找不到同步歌詞。請使用其他曲名或英文名搜尋，或加入本機 LRC 檔案。")),
		["ko-KR"] = D(("Play a track on Spotify.", "Spotify에서 곡을 재생하세요."), ("If the lyrics or timing are incorrect, you can choose another result from LRCLIB.", "가사나 타이밍이 다르면 LRCLIB에서 다른 결과를 선택할 수 있습니다."), ("Estimated timing is being used. Choose from LRCLIB to look for synchronized lyrics.", "예상 타이밍을 사용 중입니다. LRCLIB 후보에서 동기화 가사를 찾아보세요."), ("Lyrics candidates were found in LRCLIB. Choose the correct lyrics below.", "LRCLIB에서 가사 후보를 찾았습니다. 아래에서 올바른 가사를 선택하세요."), ("No synced lyrics were found. Search using another title or English name, or add a local LRC file.", "동기화 가사를 찾지 못했습니다. 다른 곡명이나 영어 이름으로 검색하거나 로컬 LRC 파일을 추가하세요.")),
		["es-ES"] = D(("Play a track on Spotify.", "Reproduce una canción en Spotify."), ("If the lyrics or timing are incorrect, you can choose another result from LRCLIB.", "Si la letra o la sincronización son incorrectas, puedes elegir otro resultado de LRCLIB."), ("Estimated timing is being used. Choose from LRCLIB to look for synchronized lyrics.", "Se usa una sincronización estimada. Elige un resultado de LRCLIB para buscar letra sincronizada."), ("Lyrics candidates were found in LRCLIB. Choose the correct lyrics below.", "Se encontraron candidatos en LRCLIB. Elige la letra correcta a continuación."), ("No synced lyrics were found. Search using another title or English name, or add a local LRC file.", "No se encontró letra sincronizada. Busca con otro título o nombre en inglés, o añade un archivo LRC local.")),
		["fr-FR"] = D(("Play a track on Spotify.", "Lancez un titre dans Spotify."), ("If the lyrics or timing are incorrect, you can choose another result from LRCLIB.", "Si les paroles ou la synchronisation sont incorrectes, choisissez un autre résultat LRCLIB."), ("Estimated timing is being used. Choose from LRCLIB to look for synchronized lyrics.", "Une synchronisation estimée est utilisée. Choisissez un résultat LRCLIB pour rechercher des paroles synchronisées."), ("Lyrics candidates were found in LRCLIB. Choose the correct lyrics below.", "Des résultats ont été trouvés dans LRCLIB. Choisissez les bonnes paroles ci-dessous."), ("No synced lyrics were found. Search using another title or English name, or add a local LRC file.", "Aucune parole synchronisée trouvée. Recherchez avec un autre titre ou un nom anglais, ou ajoutez un fichier LRC local.")),
		["de-DE"] = D(("Play a track on Spotify.", "Spielen Sie einen Titel in Spotify ab."), ("If the lyrics or timing are incorrect, you can choose another result from LRCLIB.", "Wenn Liedtext oder Timing nicht stimmen, können Sie ein anderes LRCLIB-Ergebnis wählen."), ("Estimated timing is being used. Choose from LRCLIB to look for synchronized lyrics.", "Ein geschätztes Timing wird verwendet. Wählen Sie ein LRCLIB-Ergebnis, um synchronisierten Text zu finden."), ("Lyrics candidates were found in LRCLIB. Choose the correct lyrics below.", "In LRCLIB wurden Kandidaten gefunden. Wählen Sie unten den richtigen Liedtext."), ("No synced lyrics were found. Search using another title or English name, or add a local LRC file.", "Kein synchronisierter Liedtext gefunden. Suchen Sie mit einem anderen Titel oder englischen Namen, oder fügen Sie eine lokale LRC-Datei hinzu.")),
		["pt-BR"] = D(("Play a track on Spotify.", "Reproduza uma faixa no Spotify."), ("If the lyrics or timing are incorrect, you can choose another result from LRCLIB.", "Se a letra ou a sincronização estiverem incorretas, escolha outro resultado do LRCLIB."), ("Estimated timing is being used. Choose from LRCLIB to look for synchronized lyrics.", "Uma sincronização estimada está sendo usada. Escolha um resultado do LRCLIB para procurar letra sincronizada."), ("Lyrics candidates were found in LRCLIB. Choose the correct lyrics below.", "Foram encontrados candidatos no LRCLIB. Escolha a letra correta abaixo."), ("No synced lyrics were found. Search using another title or English name, or add a local LRC file.", "Nenhuma letra sincronizada foi encontrada. Pesquise com outro título ou nome em inglês, ou adicione um arquivo LRC local.")),
		["ru-RU"] = D(("Play a track on Spotify.", "Включите трек в Spotify."), ("If the lyrics or timing are incorrect, you can choose another result from LRCLIB.", "Если текст или синхронизация неверны, выберите другой результат из LRCLIB."), ("Estimated timing is being used. Choose from LRCLIB to look for synchronized lyrics.", "Используется приблизительная синхронизация. Выберите результат LRCLIB, чтобы найти синхронный текст."), ("Lyrics candidates were found in LRCLIB. Choose the correct lyrics below.", "В LRCLIB найдены варианты текста. Выберите правильный вариант ниже."), ("No synced lyrics were found. Search using another title or English name, or add a local LRC file.", "Синхронный текст не найден. Выполните поиск по другому или английскому названию либо добавьте локальный LRC-файл."))
	};

	private static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> PlainLyricsTranslations = new Dictionary<string, IReadOnlyDictionary<string, string>>(StringComparer.OrdinalIgnoreCase)
	{
		["ja-JP"] = D(("Plain lyrics scroll continuously. Choose from LRCLIB to look for synchronized lyrics.", "同期なし歌詞は全文をスクロール表示します。LRCLIBから候補を選び、同期歌詞を探せます。")),
		["zh-CN"] = D(("Plain lyrics scroll continuously. Choose from LRCLIB to look for synchronized lyrics.", "非同步歌词会连续滚动显示。可从 LRCLIB 候选中查找同步歌词。")),
		["zh-TW"] = D(("Plain lyrics scroll continuously. Choose from LRCLIB to look for synchronized lyrics.", "非同步歌詞會連續捲動顯示。可從 LRCLIB 候選中尋找同步歌詞。")),
		["ko-KR"] = D(("Plain lyrics scroll continuously. Choose from LRCLIB to look for synchronized lyrics.", "비동기 가사는 전체가 계속 스크롤됩니다. LRCLIB 후보에서 동기화 가사를 찾아보세요.")),
		["es-ES"] = D(("Plain lyrics scroll continuously. Choose from LRCLIB to look for synchronized lyrics.", "La letra no sincronizada se desplaza de forma continua. Elige un resultado de LRCLIB para buscar letra sincronizada.")),
		["fr-FR"] = D(("Plain lyrics scroll continuously. Choose from LRCLIB to look for synchronized lyrics.", "Les paroles non synchronisées défilent en continu. Choisissez un résultat LRCLIB pour trouver des paroles synchronisées.")),
		["de-DE"] = D(("Plain lyrics scroll continuously. Choose from LRCLIB to look for synchronized lyrics.", "Unsynchronisierter Text wird fortlaufend gescrollt. Wählen Sie ein LRCLIB-Ergebnis für synchronisierten Text.")),
		["pt-BR"] = D(("Plain lyrics scroll continuously. Choose from LRCLIB to look for synchronized lyrics.", "A letra sem sincronização rola continuamente. Escolha um resultado do LRCLIB para buscar letra sincronizada.")),
		["ru-RU"] = D(("Plain lyrics scroll continuously. Choose from LRCLIB to look for synchronized lyrics.", "Несинхронизированный текст прокручивается непрерывно. Выберите вариант LRCLIB для поиска синхронного текста."))
	};

	public static string CurrentLanguage { get; private set; } = "en-US";

	public static IReadOnlyList<LanguageOption> Languages { get; } = new LanguageOption[10]
	{
		new LanguageOption("en-US", "English"),
		new LanguageOption("ja-JP", "日本語"),
		new LanguageOption("zh-CN", "简体中文"),
		new LanguageOption("zh-TW", "繁體中文"),
		new LanguageOption("ko-KR", "한국어"),
		new LanguageOption("es-ES", "Español"),
		new LanguageOption("fr-FR", "Français"),
		new LanguageOption("de-DE", "Deutsch"),
		new LanguageOption("pt-BR", "Português"),
		new LanguageOption("ru-RU", "Русский")
	};

	public static string NormalizeLanguage(string? language)
	{
		if (!string.IsNullOrWhiteSpace(language))
		{
			foreach (LanguageOption language2 in Languages)
			{
				if (string.Equals(language2.Code, language, StringComparison.OrdinalIgnoreCase))
				{
					return language2.Code;
				}
			}
		}
		return "en-US";
	}

	public static void SetCurrentLanguage(string? language)
	{
		CurrentLanguage = NormalizeLanguage(language);
	}

	public static string TranslateCurrent(string key)
	{
		return Translate(CurrentLanguage, key);
	}

	public static string Translate(string? language, string key)
	{
		string text = NormalizeLanguage(language);
		if (Translations.TryGetValue(text, out IReadOnlyDictionary<string, string> value) && value.TryGetValue(key, out var value2))
		{
			return value2;
		}
		if (OverlayTranslations.TryGetValue(text, out value) && value.TryGetValue(key, out value2))
		{
			return value2;
		}
		if (LyricsGuidanceTranslations.TryGetValue(text, out value) && value.TryGetValue(key, out value2))
		{
			return value2;
		}
		if (PlainLyricsTranslations.TryGetValue(text, out value) && value.TryGetValue(key, out value2))
		{
			return value2;
		}
		if (!RuntimeTranslations.TryGet(text, key, out value2))
		{
			return key;
		}
		return value2;
	}

	private static IReadOnlyDictionary<string, string> D(params (string Key, string Value)[] entries)
	{
		Dictionary<string, string> dictionary = new Dictionary<string, string>(StringComparer.Ordinal);
		for (int i = 0; i < entries.Length; i++)
		{
			(string Key, string Value) tuple = entries[i];
			string item = tuple.Key;
			string item2 = tuple.Value;
			dictionary[item] = item2;
		}
		return dictionary;
	}
}
